# Generated by Django 3.2.7 on 2021-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
